### ISSUE TITLE
Automate EDA notebook for meetup attendees data

### ISSUE THREAD

**Issue by suppathak** [operate-first/operate-first-data-science-community#84]
For creating a self updating EDA notebook, we will have to create a cron job that runs biweekly and updates the notebook for new meetup attendees data.

**Comment by suppathak** [comment]
@aakankshaduggal 
The data obfuscation technique, which is applied in regular basis for regular influx of data every biweekly, is done internally. The process is not shared with others, keeping attendees data security at high priority. Once we have the obfuscated data, it can be visualized through google analytics. Hence, after giving some thought, does it makes sense to explain the steps of obfuscation process in a notebook instead of doing cron job. Lmk wyt?

**Comment by aakankshaduggal** [comment]
I think it is vital that we document this process well enough for the new organizers to be able to re-create this pipeline to anonymize the attendees' data. Let's look at it this way, instead of creating a cron job for this. We should create proper documentation for recreating this process. Starting from receiving the attendees' list from the organizer, and the corresponding hash values, then anonymizing by using the obfuscation notebook, and finally storing all this data and further using it for creating a dashboard for the community metrics. I can help you with this documentation by covering the latter part of the metrics and dashboard.

Please let me know if you need any other assistance from my end.

Does this sound reasonable @MichaelClifford ?
